### ISSUE TITLE
Expose SFZ instruments

### ISSUE THREAD

**Issue by peastman** [sgossner/VCSL#24]
I notice the SFZ instruments are still hidden away where few people are ever likely to realize they exist.  Exposing them in some more visible way would make the library much more useful for people who just want a set of instruments they can use to create music.  Even if you want to keep them on their own branch, there are two simple things that would make them a lot more useful.

1. Update the README to mention that they exist and how to get them.

2. Create a Github release from the sfz branch, which will give a one-click way for people to download a set of ready to use instruments.

**Comment by sgossner** [comment]
Ok, let's do it.

I always link separately directly to the sfz's when mentioning the project, but this would probably help.

**Comment by sgossner** [comment]
Done!

**Comment by peastman** [comment]
Awesome!
