### ISSUE TITLE
Convert VCSL from WAV to FLAC format

### ISSUE THREAD

**Issue by sgossner** [sgossner/VCSL#27]
One thing I might do is convert the entire library to FLAC. It's lossless, but compressed so it'll save about 50-90% of the space when downloading, considerably better than ZIP. The disadvantage of course is FLAC is less accessible to people, so any thoughts on this are welcome!

_Originally posted by @sgossner in https://github.com/sgossner/VCSL/issues/26#issuecomment-778653322_

To reduce sample size and ease download access, the project will be converted into FLAC format.

This will require:
- [ ] Batch converting all WAV files to FLAC
- [ ] Updating all existing .SFZ files to use FLAC extension

**Comment by squinkylabs** [comment]
works for me. Luckily my player can play wav and flac, and nothing else ;-)

**Comment by toadzroc** [comment]
I'm late to this discussion, but yes, a flac version would be an excellent alternative, imho.

**Comment by sgossner** [comment]
Plans for this are on hold with intentions to release a 2.0 version of VCSL in the next 1-2 years built from the ground up with FLAC primarily.

**Comment by peastman** [comment]
I'm looking forward to it!

**Comment by thevbw** [comment]
It would certainly be nice to cut down the data size. It should also be noted, however, that FLAC doesn't support floating point format audio, so any floating point wave files would need to be converted, possibly losing data on the way.

**Comment by sgossner** [comment]
> It would certainly be nice to cut down the data size. It should also be noted, however, that FLAC doesn't support floating point format audio, so any floating point wave files would need to be converted, possibly losing data on the way.

Thank you for your note. There are no float files in VCSL and I have no plan to use floats since they waste a ton of space and are terrible for lossless compression efficiency.

I will be closing this discussion now because it is irrelevant after my comment re: VCSL 2.0. No further changes will occur with VCSL 1.0.
