### ISSUE TITLE
Can't download the library in any way

### ISSUE THREAD

**Issue by SoliDeoGloria2** [sgossner/VCSL#29]
Hi! 

I'm trying to download VSCL, but I'm not able in any way (zip, tar or Dropbox). I could at some point download a 2 Gb file which consisted of the aerophones  and cordophones -and I'm not even sure that they were in their complete form -. It always truncates before completing or delivers a partial, 512 Mb file, or something with a seemingly random value. Really weird.

Is there an alternative? I'm very interested in trying out this library...

Thanks in advance!

**Comment by sgossner** [comment]
Send me an e-mail to our support address (contact@versilstudios.net) and I'll put an alternate download option together for you.

Sam

**Comment by toadzroc** [comment]
I'm late to this discussion, but I can't D/L VCSL either, in any format or method.

I'll send an email, if you're still open to offering this alternative.

**Comment by peastman** [comment]
If the zip and tar files aren't working for you, you can always use git to clone the repository.

```
git clone https://github.com/sgossner/VCSL.git
```

**Comment by sgossner** [comment]
> I'm late to this discussion, but I can't D/L VCSL either, in any format or method.
> 
> I'll send an email, if you're still open to offering this alternative.

I've sent you a reply with some options.

The following methods are available for downloading VCSL:
- Direct github download via web browser (not recommended, tends to error out/only give partial library)
- Github Desktop to sync 'SFZ' branch to your computer (works ok but requires creating account & installing software)
- Dropbox download via web browser (usually works fine, most recommended)
- Pulse Downloader code from Versilian website (most robust/safest solution; small fee to cover expenses, requires installing & creating account with Pulse)

Refer to the product page for the most up-to-date info on download options:
https://versilian-studios.com/vcsl/

**Comment by toadzroc** [comment]
Just a follow up, I managed to get the entire lib D/L on some else's interlink, so my part of this thread is finished.
